# Generated by Django 2.2.7 on 2019-11-27 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20191124_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['regionName']},
        ),
        migrations.RenameField(
            model_name='series',
            old_name='state',
            new_name='regionName',
        ),
        migrations.RenameField(
            model_name='states',
            old_name='state',
            new_name='regionName',
        ),
    ]
