# Generated by Django 2.2.7 on 2019-11-17 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_projections_state'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='State',
            new_name='States',
        ),
        migrations.AlterModelOptions(
            name='maps',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='projections',
            options={'ordering': ['state']},
        ),
    ]

    atomic = False
