# Generated by Django 2.2.7 on 2019-11-17 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20191117_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maps',
            options={'ordering': ['country']},
        ),
        migrations.RenameField(
            model_name='maps',
            old_name='name',
            new_name='country',
        ),
    ]
