# Generated by Django 2.2.7 on 2019-11-24 11:16

from django.db import migrations, models
import map.models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20191117_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to=map.models.handle_file)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
