# Generated by Django 2.2.7 on 2019-11-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_datafile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='file',
            field=models.FileField(upload_to='data/'),
        ),
    ]
