# Generated by Django 2.2.7 on 2019-11-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20191124_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
