# Generated by Django 2.2.7 on 2019-11-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20191124_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datafile',
            options={'ordering': ['country']},
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='title',
        ),
        migrations.AddField(
            model_name='datafile',
            name='country',
            field=models.CharField(default='USA', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maps',
            name='country',
            field=models.CharField(max_length=3),
        ),
    ]
