# Generated by Django 2.2.7 on 2019-11-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_auto_20191124_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='country',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='maps',
            name='country',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
